swagger: "2.0"
info:
  description: "Приложение для поиска менторов с целью изучения информационных технологий."
  version: "1.0.0"
  title: "GetMe App"
  contact:
    email: "varindv@gmail.com"
host: "127.0.0.1"
basePath: "/api/v1/"
tags:
  - name: "mentor"
    description: "Взаимодействия с менторами"
  - name: "plan"
    description: "Взаимодействия с планом развития"
  - name: "user"
    description: "Взаимодействие с пользователем"
  - name: "auth"
    description: "Аутентификация"
schemes:
  - "https"
  - "http"
paths:
  /auth/telegram/register:
    get:
      tags:
        - "auth"
      summary: "Проверка авторизации"
      description: "Проверка авторизации через телеграм"
      produces:
        - "application/json"
      consumes:
        - "application/json"
      parameters:
        - name: "UserAuthRequest"
          in: body
          required: true
          schema:
            $ref: '#/definitions/UserAuthRequest'
      responses:
        "201":
          description: "Пользователь создан, проверка аутентификации успешна"
          schema:
            $ref: '#/definitions/User'
        "400":
          description: "Проверка переданных данных неуспешна"
          schema:
            $ref: '#/definitions/ErrResponse'
        "500":
          description: "Ошибка сервера"
          schema:
            $ref: '#/definitions/ErrResponse'
        "503":
          description: "Ошибка сервера - метод недоступен"
          schema:
            $ref: '#/definitions/ErrResponse'
  /auth/telegram/login:
    get:
      tags:
        - "auth"
      summary: "Получение сессии после отправки формы в Телеграмм"
      description: "Получение сессии после аутентефикации через Телеграм"
      produces:
        - "application/json"
      parameters:
        - name: "Token"
          in: "query"
          description: "Токен, подтверждающий авторизацию через телеграм"
          required: true
          type: "string"

      responses:
        "200":
          description: "Успешная авторизация, выставление сессионной куки"
        "500":
          description: "Ошибка сервера"
          schema:
            $ref: '#/definitions/ErrResponse'
        "400":
          description: "Ошибка в запросе - не указан токен / указан невалидный токен"
          schema:
            $ref: '#/definitions/ErrResponse'
        "503":
          description: "Ошибка - метод недоступен"
          schema:
            $ref: '#/definitions/ErrResponse'
  /auth/simple/register:
    post:
      consumes:
        - application/json
      description: create new account
      parameters:
        - description: Request body for user registration
          in: body
          name: register_info
          required: true
          schema:
            $ref: '#/definitions/RequestRegistration'
      produces:
        - application/json
      responses:
        "201":
          description: Create user successfully
          schema:
            $ref: '#/definitions/IdResponse'
        "409":
          description: user already exist
          schema:
            $ref: '#/definitions/ErrResponse'
        "418":
          description: User are authorized
        "422":
          description: invalid body in request", "nickname already exist", "incorrect
            email or password", "incorrect nickname
          schema:
            $ref: '#/definitions/ErrResponse'
        "500":
          description: can not do bd operation
          schema:
            $ref: '#/definitions/ErrResponse'
      summary: create new user
      tags:
        - auth
  /auth/simple/login:
    post:
      consumes:
        - application/json
      description: "Аутентификация пользователя через логин + пароль"
      parameters:
        - description: "Тело аутентификации"
          in: body
          name: user
          required: true
          schema:
            $ref: '#/definitions/RequestLogin'
      produces:
        - application/json
      responses:
        "200":
          description: "Успешная авторизация"
        "401":
          description: "Некорректный логин или пароль"
          schema:
            $ref: '#/definitions/ErrResponse'
        "404":
          description: "Пользователь не найден"
          schema:
            $ref: '#/definitions/ErrResponse'
        "418":
          description: "Пользователь уже авторизован"
        "422":
          description: "Некорректное тело запроса"
          schema:
            $ref: '#/definitions/ErrResponse'
        "500":
          description: "Ошибка сервера"
          schema:
            $ref: '#/definitions/ErrResponse'
      summary: login user
      tags:
        - auth
  /logout:
    post:
      consumes:
        - application/json
      description: logout user
      produces:
        - application/json
      responses:
        "201":
          description: Successfully logout
        "401":
          description: User not are authorized
        "500":
          description: server error
          schema:
            $ref: '#/definitions/ErrResponse'
      summary: logout user
      tags:
        - auth
  /auth/token:
    get:
      tags:
        - "auth"
      summary: "Получение токена"
      description: "Получение токена для подтверждения аутентификации через телеграм"
      produces:
        - "application/json"
      responses:
        "200":
          description: "Успешная авторизация, выставление сессионной куки"
          schema:
            $ref: '#/definitions/Token'
        "500":
          description: "Ошибка сервера"
          schema:
            $ref: '#/definitions/ErrResponse'
        "503":
          description: "Ошибка - метод недоступен"
          schema:
            $ref: '#/definitions/ErrResponse'



definitions:
  ErrResponse:
    properties:
      error:
        type: string
    type: object
  OkResponse:
    properties:
      OK:
        type: string
    type: object
  Token:
    type: "object"
    properties:
      token:
        type: "string"
  UserAuthRequest:
    type: "object"
    properties:
      token:
        type: "string"
      id:
        type: "integer"
        format: "int64"
      auth_date:
        type: "string"
      first_name:
        type: "string"
      last_name:
        type: "string"
      username:
        type: "string"
      photo_url:
        type: "string"
      hash:
        type: "string"
  User:
    type: "object"
    properties:
      nickname:
        type: "string"
      fullname:
        type: "string"
      about:
        type: "string"
      email:
        type: "string"
  RequestLogin:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  RequestRegistration:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  IdResponse:
    properties:
      id:
        type: integer
    type: object
