version: "3"

volumes:
  dbbackups:
  postgis-data:
  session-redis:
  mysql-data:
  cache:
services:
  ngnix-proxy:
#    image: nginx:1.23.1
    image: macbre/nginx-http3:1.23.1
    depends_on:
      - main
    expose:
      - "80"
      - "443"
    ports:
      - "443:443/tcp"
      - "443:443/udp"
      - "80:80/tcp"
      - "80:80/udp"
    volumes:
      - ./configs/certs/localhost/:/etc/nginx/ssl/
      - ./cache-nginx:/var/cache/nginx
      - ./logs-nginx:/var/log/nginx/
      - ./static:/static
      - ${NGNIX_CONFIG}:/etc/nginx/conf.d/default.conf
      - ./swagger/swagger-editor:/var/www/swagger-editor
      - ./swagger/swagger-ui:/var/www/swagger-ui
  main:
    image: getme-main
    expose:
      - "81"
    ports:
      - "81:80"
    networks:
      - default
    volumes:
      - ./api:/app/api
      - ./logs:/app/logs
      - ./media:/app/media
      - ./static:/app/static
      - ${CONFIG_DIR}:/app/configs
    depends_on:
      - getme-db
      - session-service
      - getme-cache
    environment:
      WAIT_HOSTS: getme-db:5432, getme-cache:6379
  main-2:
    image: getme-main
    expose:
      - "82"
    ports:
      - "82:80"
    networks:
      - default
    volumes:
      - ./api:/app/api
      - ./logs:/app/logs
      - ./media:/app/media
      - ./static:/app/static
      - ${CONFIG_DIR}:/app/configs
    depends_on:
      - getme-db
      - session-service
      - getme-cache
    environment:
      WAIT_HOSTS: getme-db:5432, getme-cache:6379

  main-3:
    image: getme-main
    expose:
      - "83"
#    ports:
#      - "83:80"
    networks:
      - default
    volumes:
      - ./api:/app/api
      - ./logs:/app/logs
      - ./media:/app/media
      - ./static:/app/static
      - ${CONFIG_DIR}:/app/configs
    depends_on:
      - getme-db
      - session-service
      - getme-cache
    environment:
      WAIT_HOSTS: getme-db:5432, getme-cache:6379

  test-main:
    image: getme-main
    expose:
      - "84"
    ports:
      - "84:80"
    networks:
      - default
    volumes:
      - ./api:/app/api
      - ./logs:/app/logs
      - ./media:/app/media
      - ./static:/app/static
      - ${CONFIG_DIR}:/app/configs
    depends_on:
      - getme-db
      - session-service
      - getme-cache
    environment:
      WAIT_HOSTS: getme-db:5432, getme-cache:6379

  session-service:
    image: session-service
    expose:
      - "5001"
    ports:
      - "5001:5001"
    networks:
      - default
    volumes:
      - ./logs-sessions:/app/logs
      - ${CONFIG_DIR}:/app/configs
    depends_on:
      - session-redis
    environment:
      WAIT_HOSTS: getme-db:5432
  getme-db:
    image: pg-14
    expose:
      - "5430"
    command: "postgres -c shared_preload_libraries='pg_stat_statements'"
    volumes:
      - postgis-data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=${PG_BD_PASSWORD}
      - POSTGRES_USER=${PG_BD_USERNAME}
      - POSTGRES_DB=${PG_BD_NAME}
    ports:
      - "5430:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 5G

  session-redis:
    image: "redis:alpine"
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - session-redis:/data
    restart: always

networks:
  default:
    driver: bridge