version: "3"

volumes:
  cache:
services:
  getme-cache:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    volumes:
      - cache:/data
    restart: always

networks:
  default:
    driver: bridge