// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mock is a generated GoMock package.
package mock

import (
	dto "getme-backend/internal/app/user/dto"
	entities_user "getme-backend/internal/app/user/entities"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// CreateBaseUser mocks base method.
func (m *MockUsecase) CreateBaseUser(nickname string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBaseUser", nickname)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBaseUser indicates an expected call of CreateBaseUser.
func (mr *MockUsecaseMockRecorder) CreateBaseUser(nickname interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBaseUser", reflect.TypeOf((*MockUsecase)(nil).CreateBaseUser), nickname)
}

// CreateFilledUser mocks base method.
func (m *MockUsecase) CreateFilledUser(data *dto.UserUsecase) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFilledUser", data)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFilledUser indicates an expected call of CreateFilledUser.
func (mr *MockUsecaseMockRecorder) CreateFilledUser(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFilledUser", reflect.TypeOf((*MockUsecase)(nil).CreateFilledUser), data)
}

// FindByID mocks base method.
func (m *MockUsecase) FindByID(id int64) (*dto.UserWithSkillsUsecase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*dto.UserWithSkillsUsecase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUsecaseMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUsecase)(nil).FindByID), id)
}

// FindByNickname mocks base method.
func (m *MockUsecase) FindByNickname(nickname string) (*entities_user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByNickname", nickname)
	ret0, _ := ret[0].(*entities_user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByNickname indicates an expected call of FindByNickname.
func (mr *MockUsecaseMockRecorder) FindByNickname(nickname interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByNickname", reflect.TypeOf((*MockUsecase)(nil).FindByNickname), nickname)
}

// GetMentorStatus mocks base method.
func (m *MockUsecase) GetMentorStatus(id int64) (*dto.UserStatusUsecase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMentorStatus", id)
	ret0, _ := ret[0].(*dto.UserStatusUsecase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMentorStatus indicates an expected call of GetMentorStatus.
func (mr *MockUsecaseMockRecorder) GetMentorStatus(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMentorStatus", reflect.TypeOf((*MockUsecase)(nil).GetMentorStatus), id)
}

// UpdateMentorStatus mocks base method.
func (m *MockUsecase) UpdateMentorStatus(user *dto.UserStatusUsecase) (*dto.UserStatusUsecase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMentorStatus", user)
	ret0, _ := ret[0].(*dto.UserStatusUsecase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMentorStatus indicates an expected call of UpdateMentorStatus.
func (mr *MockUsecaseMockRecorder) UpdateMentorStatus(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMentorStatus", reflect.TypeOf((*MockUsecase)(nil).UpdateMentorStatus), user)
}

// UpdateUser mocks base method.
func (m *MockUsecase) UpdateUser(user *dto.UserWithSkillsUsecase) (*dto.UserWithSkillsUsecase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", user)
	ret0, _ := ret[0].(*dto.UserWithSkillsUsecase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUsecaseMockRecorder) UpdateUser(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUsecase)(nil).UpdateUser), user)
}
