// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mock is a generated GoMock package.
package mock

import (
	dto "getme-backend/internal/app/user/dto"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// AuthSimple mocks base method.
func (m *MockUsecase) AuthSimple(login, password string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthSimple", login, password)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthSimple indicates an expected call of AuthSimple.
func (mr *MockUsecaseMockRecorder) AuthSimple(login, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthSimple", reflect.TypeOf((*MockUsecase)(nil).AuthSimple), login, password)
}

// AuthTelegram mocks base method.
func (m *MockUsecase) AuthTelegram(user *dto.UserAuthUsecase) (*dto.UserAuthUsecase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthTelegram", user)
	ret0, _ := ret[0].(*dto.UserAuthUsecase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthTelegram indicates an expected call of AuthTelegram.
func (mr *MockUsecaseMockRecorder) AuthTelegram(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthTelegram", reflect.TypeOf((*MockUsecase)(nil).AuthTelegram), user)
}

// CreateSimple mocks base method.
func (m *MockUsecase) CreateSimple(user *dto.UserSimpleRegistrationUsecase) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSimple", user)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSimple indicates an expected call of CreateSimple.
func (mr *MockUsecaseMockRecorder) CreateSimple(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSimple", reflect.TypeOf((*MockUsecase)(nil).CreateSimple), user)
}
